/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CostRouteImport } from './routes/cost'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as AgentsSourceIdRouteImport } from './routes/agents/$sourceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSourceIdRoute = AgentsSourceIdRouteImport.update({
  id: '/agents/$sourceId',
  path: '/agents/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/settings': typeof SettingsRoute
  '/agents/$sourceId': typeof AgentsSourceIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/settings': typeof SettingsRoute
  '/agents/$sourceId': typeof AgentsSourceIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/settings': typeof SettingsRoute
  '/agents/$sourceId': typeof AgentsSourceIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cost'
    | '/settings'
    | '/agents/$sourceId'
    | '/sessions/$sessionId'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cost'
    | '/settings'
    | '/agents/$sourceId'
    | '/sessions/$sessionId'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/cost'
    | '/settings'
    | '/agents/$sourceId'
    | '/sessions/$sessionId'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostRoute: typeof CostRoute
  SettingsRoute: typeof SettingsRoute
  AgentsSourceIdRoute: typeof AgentsSourceIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$sourceId': {
      id: '/agents/$sourceId'
      path: '/agents/$sourceId'
      fullPath: '/agents/$sourceId'
      preLoaderRoute: typeof AgentsSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostRoute: CostRoute,
  SettingsRoute: SettingsRoute,
  AgentsSourceIdRoute: AgentsSourceIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
